language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: aYatwEk7Y9i14jkbIDigx2H6m+2dkruGdCXGmJEJcTS0ZmtEpA/vwx0PR3KRVv1+wKX+Pka0K83yxoo97JjFNeCdSSTfOno8HCoxqDuTvASp3L22SfA+OM1Z1WjHL0J6mxvXHdCEq6IVSRHJIClHI2+ja43ZTzHxRhPSHKY5TrAEr1DKvgFxYefOC90KBBpQJdfDlq+ILzFcJyGnVdNU+eQWVKZsDri5+kYJVnJ/fqi9McOAf8iJ+3xCHb/qk7BdZNsPcD0iLAGdTlfz9r4P96reW72Qr130AeD3oQhQhWvVFiXpqNFHwPiFhjK3ZGOZGFdLRT7pfWicoAzlJT/7h9dr3bztzCFsnFcm59j+9haYBGOFIsmxAK0YGjZAPIK8K/c7LP2x4w1Qn2m2k3zgef+Bi5krAxZ28FsjespoIkZTwQT1OHlh/KTW8JSVsPZnWmqQ5w6Z4nnLkIaTZNUYmMGTMF+Rtgbgsh4EGF3z78gHpnBFTGgcMy3U3lLJD28AoNccJYPRB8+ca7GfMPzmNi7KOYCK4CLMQkq7DttoPi4rq1rFsS+8CpTcE1agN7EgMSmZsdHl3T+Wm3oYhIcz+Nvksvb6/ccrRe1vaB0EyaMGxYsMD6acH8LbSmjMoPf3Mqtx6NvqECv8D+cgrKDN26E+VWQPShstthqH835vG1U=
